import { jsPDF } from 'jspdf';
import { FloorPlan } from './types';
import { generateBOQ } from './boqEngine';
import { formatKES } from './costEstimator';
import { checkCompliance } from './complianceChecker';
import { generateTimeline } from './timelineGenerator';
import { calculateGreenScore } from './greenScoring';

// ─────────────────────────────────────────────────────────────────────────────
// Professional multi-page PDF report (client-side, jsPDF).
// ─────────────────────────────────────────────────────────────────────────────

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

const NAVY: [number, number, number] = [15, 15, 26];
const CYAN: [number, number, number] = [0, 150, 190];
const GRAY: [number, number, number] = [90, 100, 120];
const LIGHT: [number, number, number] = [235, 238, 245];

interface PdfOptions {
  floorPlanImage?: string | null; // PNG data URL of the 2D plan
}

export function generatePdfReport(plan: FloorPlan, options: PdfOptions = {}): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const report = generateBOQ(plan, { region: undefined });
  const summary = report.grandSummary;
  const compliance = checkCompliance(plan, plan.climateZone);
  const timeline = generateTimeline(plan);
  const green = calculateGreenScore(plan);

  const today = new Date().toLocaleDateString('en-KE', { year: 'numeric', month: 'long', day: 'numeric' });
  const totalRooms = plan.floors.reduce((s, f) => s + f.rooms.length, 0);

  let pageNo = 0;

  const footer = () => {
    pageNo++;
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(
      'Generated by BuildAI  |  Not a substitute for professional architectural & structural engineering drawings  |  ' + today,
      PAGE_W / 2,
      PAGE_H - 8,
      { align: 'center' },
    );
    doc.text(String(pageNo), PAGE_W - MARGIN, PAGE_H - 8, { align: 'right' });
  };

  const sectionTitle = (title: string, y: number): number => {
    doc.setFillColor(...CYAN);
    doc.rect(MARGIN, y, CONTENT_W, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(title, MARGIN + 3, y + 5.6);
    doc.setFont('helvetica', 'normal');
    return y + 13;
  };

  // ── PAGE 1 — COVER ──────────────────────────────────────────────────────
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
  doc.setTextColor(0, 212, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(40);
  doc.text('BuildAI', PAGE_W / 2, 70, { align: 'center' });
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('Building Analysis Report', PAGE_W / 2, 82, { align: 'center' });

  doc.setDrawColor(...CYAN);
  doc.setLineWidth(0.5);
  doc.line(MARGIN + 30, 90, PAGE_W - MARGIN - 30, 90);

  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(plan.buildingName || 'Untitled Building', PAGE_W / 2, 108, { align: 'center' });

  // Cover stats
  doc.setFontSize(11);
  doc.setTextColor(180, 190, 210);
  const stats = [
    `Total Area:  ${plan.totalAreaSqMeters.toFixed(1)} m²`,
    `Floors:  ${plan.floors.length}`,
    `Rooms:  ${totalRooms}`,
    `Estimated Cost:  ${formatKES(summary.grandTotal)}`,
    `Date:  ${today}`,
  ];
  stats.forEach((s, i) => doc.text(s, PAGE_W / 2, 124 + i * 8, { align: 'center' }));

  // Floor plan thumbnail
  if (options.floorPlanImage) {
    try {
      const imgW = 120;
      const imgH = 80;
      doc.setFillColor(255, 255, 255);
      doc.rect((PAGE_W - imgW) / 2 - 2, 172, imgW + 4, imgH + 4, 'F');
      doc.addImage(options.floorPlanImage, 'PNG', (PAGE_W - imgW) / 2, 174, imgW, imgH, undefined, 'FAST');
    } catch {
      /* ignore image failures */
    }
  }
  doc.setFontSize(8);
  doc.setTextColor(120, 130, 150);
  doc.text('Built for the WFCP World Congress 2026 — SDG 9: Innovation & Infrastructure', PAGE_W / 2, PAGE_H - 16, {
    align: 'center',
  });

  // ── PAGE 2 — FLOOR PLAN ─────────────────────────────────────────────────
  doc.addPage();
  let y = sectionTitle('Floor Plan Drawing', MARGIN);
  if (options.floorPlanImage) {
    try {
      const imgW = CONTENT_W;
      const imgH = (imgW * 2) / 3;
      doc.setFillColor(...LIGHT);
      doc.rect(MARGIN, y, imgW, imgH, 'F');
      doc.addImage(options.floorPlanImage, 'PNG', MARGIN, y, imgW, imgH, undefined, 'FAST');
      y += imgH + 6;
    } catch {
      y += 4;
    }
  }
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(
    `Orientation: ${plan.orientation || 'N'}   |   Scale: not to scale (indicative)   |   ${plan.floors.length} floor(s)`,
    MARGIN,
    y + 2,
  );
  footer();

  // ── PAGE 3 — ROOM SCHEDULE ──────────────────────────────────────────────
  doc.addPage();
  y = sectionTitle('Room Schedule', MARGIN);
  const roomCols = [
    { title: 'Room', w: 52 },
    { title: 'Type', w: 36 },
    { title: 'Floor', w: 34 },
    { title: 'Area (m²)', w: 28 },
    { title: 'Finish', w: 28 },
  ];
  y = tableHeader(doc, roomCols, y);
  let grandArea = 0;
  for (const f of plan.floors) {
    for (const r of f.rooms) {
      const area = r.widthMeters * r.depthMeters;
      grandArea += area;
      y = tableRow(
        doc,
        roomCols,
        [r.name, r.type.replace(/_/g, ' '), f.floorName, area.toFixed(1), (r.floorFinish || 'tile').replace(/_/g, ' ')],
        y,
      );
      if (y > PAGE_H - 24) {
        footer();
        doc.addPage();
        y = sectionTitle('Room Schedule (cont.)', MARGIN);
        y = tableHeader(doc, roomCols, y);
      }
    }
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  doc.text(`Total Floor Area: ${grandArea.toFixed(1)} m²`, MARGIN, y + 4);
  doc.setFont('helvetica', 'normal');
  footer();

  // ── PAGES 4-5 — BILL OF QUANTITIES ──────────────────────────────────────
  doc.addPage();
  y = sectionTitle('Bill of Quantities', MARGIN);
  const boqCols = [
    { title: 'Description', w: 86 },
    { title: 'Qty', w: 20 },
    { title: 'Unit', w: 16 },
    { title: 'Rate', w: 26 },
    { title: 'Amount', w: 30 },
  ];
  for (const el of report.elements) {
    if (y > PAGE_H - 40) {
      footer();
      doc.addPage();
      y = sectionTitle('Bill of Quantities (cont.)', MARGIN);
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...CYAN);
    doc.text(`ELEMENT ${el.elementNumber}: ${el.elementName}`, MARGIN, y);
    y += 4;
    doc.setFont('helvetica', 'normal');
    for (const ss of el.subSections) {
      if (y > PAGE_H - 28) {
        footer();
        doc.addPage();
        y = sectionTitle('Bill of Quantities (cont.)', MARGIN);
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...GRAY);
      doc.text(`${ss.code}  ${ss.name}`, MARGIN, y);
      doc.setFont('helvetica', 'normal');
      y += 3.5;
      y = tableHeader(doc, boqCols, y);
      for (const it of ss.items) {
        y = tableRow(
          doc,
          boqCols,
          [`${it.itemCode}  ${it.description}`, formatNum(it.quantity), it.unit, formatNum(it.rate), formatNum(it.amount)],
          y,
          7.5,
        );
        if (y > PAGE_H - 24) {
          footer();
          doc.addPage();
          y = sectionTitle('Bill of Quantities (cont.)', MARGIN);
          y = tableHeader(doc, boqCols, y);
        }
      }
    }
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...NAVY);
    doc.setFontSize(8.5);
    doc.text(`Element ${el.elementNumber} subtotal: ${formatKES(el.subtotal)}`, PAGE_W - MARGIN, y + 1, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    y += 7;
  }
  // Totals box
  if (y > PAGE_H - 50) {
    footer();
    doc.addPage();
    y = sectionTitle('BOQ Summary', MARGIN);
  }
  y += 2;
  doc.setFillColor(...LIGHT);
  doc.rect(MARGIN, y, CONTENT_W, 30, 'F');
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  const totalsLines = [
    ['Subtotal', formatKES(summary.subtotalBeforeContingency)],
    ['Contingency (10%)', formatKES(summary.contingency)],
    ['VAT (16%)', formatKES(summary.vat)],
  ];
  totalsLines.forEach((line, i) => {
    doc.text(line[0], MARGIN + 3, y + 6 + i * 6);
    doc.text(line[1], PAGE_W - MARGIN - 3, y + 6 + i * 6, { align: 'right' });
  });
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('GRAND TOTAL', MARGIN + 3, y + 27);
  doc.text(formatKES(summary.grandTotal), PAGE_W - MARGIN - 3, y + 27, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  footer();

  // ── PAGE 6 — COST SUMMARY ───────────────────────────────────────────────
  doc.addPage();
  y = sectionTitle('Cost Summary', MARGIN);
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text(`Total Estimated Cost: ${formatKES(summary.grandTotal)}`, MARGIN, y);
  y += 7;
  doc.setFontSize(10);
  doc.text(`Cost per m² (incl. VAT): ${formatKES(summary.costPerSqMeterInclVAT)}   |   excl. VAT: ${formatKES(summary.costPerSqMeterExclVAT)}`, MARGIN, y);
  y += 10;
  const costCols = [
    { title: 'Element', w: 100 },
    { title: 'Amount (KES)', w: 48 },
    { title: '% of build', w: 30 },
  ];
  y = tableHeader(doc, costCols, y);
  for (const es of summary.elementSubtotals) {
    y = tableRow(doc, costCols, [es.element, formatNum(es.amount), es.percentage.toFixed(1) + '%'], y);
  }
  y += 4;
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text('Benchmark bands (KES/m²):  Basic 25,000  •  Standard 35,000  •  Premium 50,000', MARGIN, y);
  footer();

  // ── PAGE 7 — COMPLIANCE ─────────────────────────────────────────────────
  doc.addPage();
  y = sectionTitle('Compliance Report', MARGIN);
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text(`Overall Score: ${compliance.passed}/${compliance.total} checks passed  (${compliance.score}%)`, MARGIN, y);
  y += 9;
  for (const c of compliance.checks) {
    if (y > PAGE_H - 30) {
      footer();
      doc.addPage();
      y = sectionTitle('Compliance Report (cont.)', MARGIN);
    }
    const symbol = c.status === 'pass' ? '[PASS]' : c.status === 'fail' ? '[FAIL]' : '[WARN]';
    const col: [number, number, number] = c.status === 'pass' ? [16, 140, 90] : c.status === 'fail' ? [200, 50, 50] : [200, 150, 30];
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...col);
    doc.text(symbol, MARGIN, y);
    doc.setTextColor(...NAVY);
    doc.text(c.description, MARGIN + 18, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    const detailLines = doc.splitTextToSize(`${c.details}  (${c.regulation})`, CONTENT_W - 18);
    doc.text(detailLines, MARGIN + 18, y + 4);
    y += 5 + detailLines.length * 3.6 + 2;
  }
  footer();

  // ── PAGE 8 — STRUCTURAL & GREEN NOTES ───────────────────────────────────
  doc.addPage();
  y = sectionTitle('Structural Notes & Specifications', MARGIN);
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  const notes = [
    `Foundation: ${plan.foundation?.type || 'strip'} foundation, depth ${plan.foundation?.depthMeters || 1.0}m, ${(plan.foundation?.material || 'reinforced concrete').replace(/_/g, ' ')}.`,
    `Walling: External 200mm natural stone / blocks; internal 150mm concrete blocks.`,
    `Structure: ${(plan.structure?.system || 'load_bearing_walls').replace(/_/g, ' ')}.`,
    plan.structure?.beamNotes ? `Beams: ${plan.structure.beamNotes}` : `Beams: provide ring beam at lintel and wall-plate level.`,
    plan.structure?.columnNotes ? `Columns: ${plan.structure.columnNotes}` : '',
    `Roofing: ${(plan.roofing?.type || 'gable')} roof, ${(plan.roofing?.material || 'corrugated iron sheets').replace(/_/g, ' ')}, pitch ${plan.roofing?.pitchDegrees || 25}°.`,
  ].filter(Boolean);
  for (const n of notes) {
    const lines = doc.splitTextToSize('•  ' + n, CONTENT_W);
    doc.text(lines, MARGIN, y);
    y += lines.length * 4.4 + 2;
  }

  y += 4;
  y = sectionTitle('Construction Timeline', y);
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  doc.text(
    `Estimated duration: ${timeline.totalWeeks} weeks (~${timeline.totalMonths} months).  Peak crew: ${timeline.peakCrew} workers.`,
    MARGIN,
    y,
  );
  y += 8;

  y = sectionTitle('Green Building Score', y);
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text(`Score: ${green.totalScore}/100  —  Grade ${green.grade}`, MARGIN, y);
  y += 7;
  doc.setFontSize(8.5);
  doc.setTextColor(...GRAY);
  for (const cat of green.categories) {
    doc.text(`${cat.name}: ${cat.earnedPoints}/${cat.maxPoints}`, MARGIN, y);
    y += 4.6;
  }
  footer();

  doc.save(`${(plan.buildingName || 'BuildAI').replace(/\s+/g, '_')}_Report.pdf`);
}

// ── Small table helpers ──────────────────────────────────────────────────────

interface Col {
  title: string;
  w: number;
}

function tableHeader(doc: jsPDF, cols: Col[], y: number): number {
  doc.setFillColor(40, 50, 75);
  doc.rect(MARGIN, y, CONTENT_W, 6, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  let x = MARGIN + 2;
  for (const c of cols) {
    doc.text(c.title, x, y + 4);
    x += c.w;
  }
  doc.setFont('helvetica', 'normal');
  return y + 8;
}

function tableRow(doc: jsPDF, cols: Col[], values: string[], y: number, fontSize = 8.5): number {
  doc.setTextColor(40, 45, 60);
  doc.setFontSize(fontSize);
  let x = MARGIN + 2;
  let maxLines = 1;
  const wrapped = values.map((v, i) => {
    const lines = doc.splitTextToSize(String(v), cols[i].w - 2);
    maxLines = Math.max(maxLines, lines.length);
    return lines;
  });
  wrapped.forEach((lines, i) => {
    doc.text(lines, x, y + 3);
    x += cols[i].w;
  });
  const rowH = maxLines * 3.6 + 1.5;
  doc.setDrawColor(220, 225, 235);
  doc.setLineWidth(0.1);
  doc.line(MARGIN, y + rowH, PAGE_W - MARGIN, y + rowH);
  return y + rowH;
}

function formatNum(n: number): string {
  return Math.round(n).toLocaleString('en-KE');
}
